# -*- coding: utf-8 -*-
"""Soczyste rabaty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfU5lwdNa2GOPWmQ9-URaf30VnlBzQC0
"""

#importowanie potrzebnych bibliotek
import os
import openpyxl
import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import plotly.express as px
import plotly.graph_objects as go
from urllib.request import urlopen
import json
import io
import datetime
import re



st.set_page_config(page_title='Monitoringi AUTOMATY', layout='wide')


sekcja = st.sidebar.radio(
    'Wybierz monitoring:',
    ('Ketoprofen','Oferta sezonowa','Standy wrzesień-marzec','Zimowe wzmocnienie odporności','Zgaginstop')
 )

tabs_font_css = """
<style>
div[class*="stTextInput"] label {
  font-size: 26px;
  color: black;
}
div[class*="stSelectbox"] label {
  font-size: 26px;
  color: black;
}
</style>
"""
#POTRZEBNE FUNKCJE
#1 Funkcja do wyodrębnienia wartości procentowej
def extract_percentage(text):
    import re
    match = re.search(r'(\d+,\d+|\d+)%', text)
    return match.group(0) if match else ''

#2 Funkcja do konwersji wartości procentowej na float
def percentage_to_float(percentage_str):
    if pd.isna(percentage_str) or not percentage_str:
        return 0.0  # Zmieniono na 0.0, aby brakujące wartości były traktowane jako 0
    # Zamiana przecinka na kropkę, usunięcie znaku '%'
    return float(percentage_str.replace(',', '.').replace('%', ''))

def extract_numbers_as_text(text):
    numbers = re.findall(r'\d+', text)
    return f"{numbers[0]}+{numbers[1]}" if len(numbers) >= 2 else None


dzisiejsza_data = datetime.datetime.now().strftime("%d.%m.%Y")



############################################################################# Standy wrzesień-marzec################################################################
if sekcja == 'Standy wrzesień-marzec':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
        label = "Wrzuć plik Cykl - Standy wrzesień-marzec"
    )
    if df:
        df = pd.read_excel(df, sheet_name = 'Rabat', skiprows = 16, usecols = [1,2,9])
        st.write(df.head())


    #usuń braki danych z Kod klienta
    df = df.dropna(subset=['Kod klienta'])

    # klient na całkowite
    df['KLIENT'] = df['KLIENT'].astype(int)
    df['Kod klienta'] = df['Kod klienta'].astype(int)

    # Zmiana nazw kolumn
    df = df.rename(columns={'0.16.2': '16'})

    #Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
    df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['16']).lower() else '', axis=1)

    #SPRAWDZENIE CZY DZIAŁA
    #df[df['SIECIOWY'] == 'SIECIOWY']
    #DZIAŁA :)

    
    # Zastosowanie funkcji do kolumn '12' i '14'
    df['16_percent'] = df['16'].apply(extract_percentage)


    # Konwersja kolumn '12_percent' i '14_percent' na liczby zmiennoprzecinkowe
    df['16_percent'] = df['16_percent'].apply(percentage_to_float)

    # Dodaj nową kolumnę 'max_percent' z maksymalnymi wartościami z kolumn '12_percent' i '14_percent'
    df['max_percent'] = df[['16_percent']].max(axis=1)

    # Wybierz wiersze, gdzie 'max_percent' nie jest równa 0
    filtered_df = df[df['max_percent'] != 0]

    standard = filtered_df[filtered_df['SIECIOWY'] != 'SIECIOWY']
    powiazanie = filtered_df[filtered_df['SIECIOWY'] == 'SIECIOWY']

    #len(standard), len(powiazanie), len(filtered_df)

    standard_ost = standard[['Kod klienta', 'max_percent']]

    powiazanie = powiazanie[['KLIENT','Kod klienta','max_percent']]


    #TERAZ IMS
    ims = st.file_uploader(
        label = "Wrzuć plik ims_nhd"
    )

    if ims:
        ims = pd.read_excel(ims, usecols=[0,2,19,21])
        st.write(ims.head())

    ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
    ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]

    wynik_df = pd.merge(powiazanie, ims, left_on='KLIENT', right_on='Klient', how='left')

    #Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
    wynik_df = wynik_df[['KLIENT','APD_kod_SAP_apteki', 'max_percent']]


    #to są kody SAP
    wynik_df1 = wynik_df.rename(columns={'APD_kod_SAP_apteki': 'Kod klienta'})
    wynik_df1 = wynik_df1[['Kod klienta','max_percent']]
    #wynik_df1

    #to są kody powiazan
    wynik_df2 = wynik_df.rename(columns={'KLIENT': 'Kod klienta'})
    wynik_df2 = wynik_df2[['Kod klienta','max_percent']]
    #wynik_df2

    #POŁĄCZYĆ wynik_df z standard_ost
    polaczone = pd.concat([standard_ost, wynik_df1, wynik_df2], axis = 0)
  
    posortowane = polaczone.sort_values(by='max_percent', ascending=False)

    ostatecznie = posortowane.drop_duplicates(subset='Kod klienta')


    st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
    excel_file = io.BytesIO()
    with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        ostatecznie.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz, jeśli to pierwszy monitoring',
        data=excel_file,
        file_name='czy_dodac.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    #plik z poprzedniego monitoringu
    poprzedni = st.file_uploader(
        label = "Wrzuć plik z poprzedniego monitoringu"
    )

    if poprzedni:
        poprzedni = pd.read_excel(poprzedni)
        st.write(poprzedni.head())

    poprzedni = poprzedni.rename(columns={'max_percent': 'old_percent'})
    # Wykonanie left join, dodanie 'old_percent' do pliku 'ostatecznie'
    result = ostatecznie.merge(poprzedni[['Kod klienta', 'old_percent']], on='Kod klienta', how='left')
    result['old_percent'] = result['old_percent'].fillna(0)
    result['Czy dodać'] = result.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)
    st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')

    excel_file1 = io.BytesIO()
    with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku1 = f"STANDY_w-m_{dzisiejsza_data}.xlsx"
    #Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz',
        data=excel_file1,
        file_name=nazwa_pliku1,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    result = result.drop(columns=['old_percent', 'Czy dodać'])


    st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
    excel_file2 = io.BytesIO()
    with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku = f"FM_STANDY_w-m_{dzisiejsza_data}.xlsx"
    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz nowy plik FORMUŁA MAX',
        data=excel_file2,
        file_name = nazwa_pliku,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

############################################################################### ZIMOWE WZMOCNIENIE ODPORNOŚCI  ##############################################################################################
if sekcja == 'Zimowe wzmocnienie odporności':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
    label = "Wrzuć plik - Zimowe wzmocnienie odporności"
    )
    if df:
        df = pd.read_excel(df, sheet_name = 'Rabat', skiprows = 13, usecols = [1,3,10])
        st.write(df.head())
        
        #usuń braki danych z Kod klienta
    df = df.dropna(subset=['Kod SAP'])

    # klient na całkowite
    df = df[df['Klient'] != '(puste)']
    df['Klient'] = df['Klient'].astype(int)
    df['Kod SAP'] = df['Kod SAP'].astype(int)

    # Zmiana nazw kolumn
    #df = df.rename(columns={'0.12.1': '12', '0.14.1': '14'})

    #Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
    df['SIECIOWY'] = df.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)

    #SPRAWDZENIE CZY DZIAŁA
    df[df['SIECIOWY'] == 'SIECIOWY']
    #DZIAŁA :)

    
    # Zastosowanie funkcji do kolumn '12' i '14'
    df['Pakiet'] = df['Pakiet'].apply(extract_percentage)
    #df['14_percent'] = df['14'].apply(extract_percentage)


    # Konwersja kolumn '12_percent' i '14_percent' na liczby zmiennoprzecinkowe
    df['Pakiet'] = df['Pakiet'].apply(percentage_to_float)
    #df['14_percent'] = df['14_percent'].apply(percentage_to_float)

    # Dodaj nową kolumnę 'max_percent' z maksymalnymi wartościami z kolumn '12_percent' i '14_percent'
    df['max_percent'] = df[['Pakiet']].max(axis=1)

    # Wybierz wiersze, gdzie 'max_percent' nie jest równa 0
    filtered_df = df[df['max_percent'] != 0]

    standard = filtered_df[filtered_df['SIECIOWY'] != 'SIECIOWY']
    powiazanie = filtered_df[filtered_df['SIECIOWY'] == 'SIECIOWY']

    #len(standard), len(powiazanie), len(filtered_df)

    standard_ost = standard[['Kod SAP', 'max_percent']]

    powiazanie = powiazanie[['Klient','Kod SAP','max_percent']]


    #TERAZ IMS
    ims = st.file_uploader(
        label = "Wrzuć plik ims_nhd"
    )

    if ims:
        ims = pd.read_excel(ims, usecols=[0,2,19,21])
        st.write(ims.head())

    ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
    ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]

    wynik_df = pd.merge(powiazanie, ims, left_on='Klient', right_on='Klient', how='left')

    #Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
    wynik_df = wynik_df[['Klient','APD_kod_SAP_apteki', 'max_percent']]


    #to są kody SAP
    wynik_df1 = wynik_df.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
    wynik_df1 = wynik_df1[['Kod SAP','max_percent']]
    #wynik_df1

    #to są kody powiazan
    wynik_df2 = wynik_df.rename(columns={'Klient': 'Kod SAP'})
    wynik_df2 = wynik_df2[['Kod SAP','max_percent']]
    #wynik_df2

    #POŁĄCZYĆ wynik_df z standard_ost
    polaczone = pd.concat([standard_ost, wynik_df1, wynik_df2], axis = 0)
  
    posortowane = polaczone.sort_values(by='max_percent', ascending=False)

    ostatecznie = posortowane.drop_duplicates(subset='Kod SAP')


    st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
    excel_file = io.BytesIO()
    with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        ostatecznie.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz, jeśli to pierwszy monitoring',
        data=excel_file,
        file_name='czy_dodac.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    #plik z poprzedniego monitoringu
    poprzedni = st.file_uploader(
        label = "Wrzuć plik z poprzedniego monitoringu"
    )

    if poprzedni:
        poprzedni = pd.read_excel(poprzedni)
        st.write(poprzedni.head())

    poprzedni = poprzedni.rename(columns={'max_percent': 'old_percent'})
    # Wykonanie left join, dodanie 'old_percent' do pliku 'ostatecznie'
    result = ostatecznie.merge(poprzedni[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
    result['old_percent'] = result['old_percent'].fillna(0)
    result['Czy dodać'] = result.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)
    st.write('Kliknij aby pobrać plik z kodami, które kody należy dodać')

    excel_file1 = io.BytesIO()
    with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku1 = f"Zimowe_wzmocnienie_odporności_{dzisiejsza_data}.xlsx"
    #Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz',
        data=excel_file1,
        file_name=nazwa_pliku1,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

    result = result.drop(columns=['old_percent', 'Czy dodać'])


    st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')
    excel_file2 = io.BytesIO()
    with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
        result.to_excel(writer, index=False, sheet_name='Sheet1')
    excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

    nazwa_pliku = f"FM_Zimowe_wzmocnienie_odporności_{dzisiejsza_data}.xlsx"
    # Umożliwienie pobrania pliku Excel
    st.download_button(
        label='Pobierz nowy plik FORMUŁA MAX',
        data=excel_file2,
        file_name = nazwa_pliku,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )


################################################### Ketoprofen ###################################################
if sekcja == 'Ketoprofen':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
        label="Wrzuć plik - Ketoprofen"
    )
    
    if df:
        # Pobieramy listę dostępnych arkuszy
        xls = pd.ExcelFile(df)
        
        # Sprawdzamy, które arkusze są dostępne i wczytujemy odpowiednie dane
        if 'Rabat' in xls.sheet_names:
            Lr = pd.read_excel(df, sheet_name='Rabat', skiprows=13, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat:")
            st.write(Lr.head())


        # Sprawdzamy, które arkusze są dostępne i wczytujemy odpowiednie dane
        if 'Gratis' in xls.sheet_names:
            Lg = pd.read_excel(df, sheet_name='Gratis', skiprows=14, usecols=[1, 3, 9])
            st.write("Dane z arkusza Gratis:")
            st.write(Lg.head())



        #usuń braki danych z Kod klienta
        
        Lr = Lr.dropna(subset=['Pakiet']) 
        Lg = Lg.dropna(subset=['Pakiet']) 

        Lg = Lg[~Lg['Pakiet'].str.lower().str.contains('brak')]

        Lr = Lr.dropna(subset=['Klient'])
        # klient na całkowite
        Lr['Klient'] = Lr['Klient'].astype(int)
        Lg['Klient'] = Lg['Klient'].astype(int)



        Lr.columns=['Klient','Kod SAP','Pakiet']
 
        
        # Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
        Lr['SIECIOWY'] = Lr.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
        Lg['SIECIOWY'] = Lg.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)

        Lr['Pakiet'] = Lr['Pakiet'].apply(extract_percentage)

        Lg['pakiet'] = Lg['Pakiet'].apply(extract_numbers_as_text)
        Lg
        Lg = Lg[Lg["pakiet"].isin(["50+17", "100+40"])]
        Lg
        Lg["pakiet"] = "5+2"
        Lg


        #Lg

        # na zmiennoprzecinkowe
        Lr['Pakiet'] = Lr['Pakiet'].apply(percentage_to_float)
    
        # Dodaj nową kolumnę 'max_percent'
        Lr1 = Lr[Lr['SIECIOWY'] == 'SIECIOWY']
        Lr2 = Lr[Lr['SIECIOWY'] != 'SIECIOWY']
        Lr1['max_percent'] = Lr1[['Pakiet']].max(axis=1)
        Lr2['max_percent'] = Lr2[['Pakiet']].max(axis=1)
        
        ###### 1 to SIECIOWI, 2 to punkt dostaw
        Lr1 = Lr1[['Klient','Kod SAP','max_percent']]
        Lr2 = Lr2[['Kod SAP','max_percent']]


        Lg1 = Lg[Lg['SIECIOWY'] == 'SIECIOWY']
        Lg2 = Lg[Lg['SIECIOWY'] != 'SIECIOWY']

        
        #### p
        Lg1 = Lg1[['Klient','Kod SAP','pakiet']]
        Lg2 = Lg2[['Kod SAP','pakiet']]
        
        stand_lr = Lr2
        pow_lr = Lr1

        stand_lg = Lg2
        pow_lg = Lg1
        
        #TERAZ IMS
        ims = st.file_uploader(
            label = "Wrzuć plik ims_nhd"
        )
    
        if ims:
            ims = pd.read_excel(ims, usecols=[0,2,19,21])
            st.write(ims.head())
    
        ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
        ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]
    
        wynik_df_lr = pd.merge(pow_lr, ims, left_on='Klient', right_on='Klient', how='left')
        wynik_df_lg = pd.merge(pow_lg, ims, left_on='Klient', right_on='Klient', how='left')
    
        # Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
        wynik_df_lr = wynik_df_lr[['Klient','APD_kod_SAP_apteki', 'max_percent']]
        wynik_df_lg = wynik_df_lg[['Klient','APD_kod_SAP_apteki', 'pakiet']]
    
        #to są kody SAP
        wynik_df1_lr = wynik_df_lr.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1_lr = wynik_df1_lr[['Kod SAP','max_percent']]

        wynik_df1_lg = wynik_df_lg.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1_lg = wynik_df1_lg[['Kod SAP','pakiet']]

        #wynik_df1
    
        #to są kody powiazan
        wynik_df2_lr = wynik_df_lr.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2_lr = wynik_df2_lr[['Kod SAP','max_percent']]

        wynik_df2_lg = wynik_df_lg.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2_lg = wynik_df2_lg[['Kod SAP','pakiet']]

        #wynik_df2

        #POŁĄCZYĆ wynik_df z standard_ost
        polaczone_lr = pd.concat([stand_lr, wynik_df1_lr, wynik_df2_lr], axis = 0)

        polaczone_lg = pd.concat([stand_lg, wynik_df1_lg, wynik_df2_lg], axis = 0)
  
        posortowane_lr = polaczone_lr.sort_values(by='max_percent', ascending=False)

        ostatecznie_lr = posortowane_lr.drop_duplicates(subset='Kod SAP')
        ostatecznie_lr = ostatecznie_lr[ostatecznie_lr['max_percent'] != 0]


        ostatecznie_lg = polaczone_lg.drop_duplicates(subset=['Kod SAP', 'pakiet'])

        # ostatecznie_lg
        
        st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
        excel_file = io.BytesIO()

        with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        # Jeśli dane BRAZOFLAMIN istnieją, zapisz je w odpowiednim arkuszu
            if 'ostatecznie_lr' in locals():
                ostatecznie_lr.to_excel(writer, index=False, sheet_name='Rabat')

            if 'ostatecznie_lg' in locals():
                ostatecznie_lg.to_excel(writer, index=False, sheet_name='Gratis')

        excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

         # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz, jeśli to pierwszy monitoring',
            data=excel_file,
            file_name='czy_dodac.xlsx',
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
    
        # Plik z poprzedniego monitoringu
        poprzedni = st.file_uploader(
            label="Wrzuć plik z poprzedniego monitoringu"
        )
    
        if poprzedni:
            xls = pd.ExcelFile(poprzedni)  # Pobranie pliku z arkuszami
    
        # Wczytanie danych z odpowiednich arkuszy
        if 'Rabat' in xls.sheet_names:
            poprzedni_lr = pd.read_excel(poprzedni, sheet_name='Rabat')
            st.write('Poprzedni monitoring - Rabat:')
            st.write(poprzedni_lr.head())

        if 'Gratis' in xls.sheet_names:
            poprzedni_lg = pd.read_excel(poprzedni, sheet_name='Gratis')
            st.write('Poprzedni monitoring - Gratis :')
            st.write(poprzedni_lg.head())

        # Przetwarzanie 
        if 'ostatecznie_lr' in locals() and 'poprzedni_lr' in locals():
            poprzedni_lr = poprzedni_lr.rename(columns={'max_percent': 'old_percent'})
            result_lr = ostatecznie_lr.merge(poprzedni_lr[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
            result_lr['old_percent'] = result_lr['old_percent'].fillna(0)
            result_lr['Czy dodać'] = result_lr.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)

        if 'ostatecznie_lg' in locals() and 'poprzedni_lg' in locals():
            # Zmień nazwę kolumny 'pakiet' na 'old_pakiet' w poprzedni_lg
            # poprzedni_lg = poprzedni_lg.rename(columns={'pakiet': 'old_pakiet'})
            # Dodaj poprzedni_lg na dole ostatecznie_lg
            result_lg = pd.concat([ostatecznie_lg, poprzedni_lg], ignore_index=True)
            # Usuń duplikaty na podstawie kluczowych kolumn (zachowując pierwsze wystąpienie)
            result_lg = result_lg.drop_duplicates(subset=['Kod SAP', 'pakiet'], keep='first')
            # Oznacz nowe wiersze (takie, które nie były w poprzedni_lg)
            result_lg['Czy dodać'] = result_lg.apply(lambda row: 'DODAJ' if row['Kod SAP'] not in poprzedni_lg['Kod SAP'].values 
                                                     or row['pakiet'] not in poprzedni_lg['pakiet'].values else '', axis=1)


        # Zapisywanie plików do Excela
        excel_file1 = io.BytesIO()
        with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
            if 'result_lr' in locals():
                result_lr.to_excel(writer, index=False, sheet_name='Rabat')

            if 'result_lg' in locals():
                result_lg.to_excel(writer, index=False, sheet_name='Gratis')


        excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

        # Definiowanie nazwy pliku
        nazwa_pliku = f"KETOPROFEN_{dzisiejsza_data}.xlsx"
        # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Kliknij aby pobrać plik z kodami, które kody należy dodać',
            data=excel_file1,
            file_name=nazwa_pliku,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )

        result_lr = result_lr.drop(columns=['old_percent', 'Czy dodać'])
        result_lg = result_lg.drop(columns=['Czy dodać'])
        # result_lg = result_lg.drop(columns=['old_pakiet', 'Czy dodać'])

        st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')

        # Tworzenie pliku Excel w pamięci
        excel_file2 = io.BytesIO()
    
        # Zapis do pliku Excel w pamięci
        with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
            result_lr.to_excel(writer, index=False, sheet_name='Rabat')
            result_lg.to_excel(writer, index=False, sheet_name='Gratis')


        # Resetowanie wskaźnika do początku pliku
        excel_file2.seek(0) 
    
        # Definiowanie nazwy pliku
        nazwa_pliku = f"FM_KETOPROFEN_{dzisiejsza_data}.xlsx"
    
        # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz nowy plik FORMUŁA MAX',
            data=excel_file2,
            file_name=nazwa_pliku,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )


################################################### Zgaginstop ###################################################
if sekcja == 'Zgaginstop':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
        label="Wrzuć plik - Zgaginstop"
    )
    
    if df:
        # Pobieramy listę dostępnych arkuszy
        xls = pd.ExcelFile(df)
        
        # Sprawdzamy, które arkusze są dostępne i wczytujemy odpowiednie dane
        if 'Rabat Zgaginstop 24' in xls.sheet_names:
            Lr = pd.read_excel(df, sheet_name='Rabat Zgaginstop 24', skiprows=13, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat Zgaginstop 24:")
            st.write(Lr.head())

        if 'Rabat Zgaginstop 48' in xls.sheet_names:
            Lra = pd.read_excel(df, sheet_name='Rabat Zgaginstop 48', skiprows=13, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat Zgaginstop 48:")
            st.write(Lra.head())


        # Sprawdzamy, które arkusze są dostępne i wczytujemy odpowiednie dane
        if 'Gratis Zgaginstop 24' in xls.sheet_names:
            Lg = pd.read_excel(df, sheet_name='Gratis Zgaginstop 24', skiprows=14, usecols=[1, 3, 9])
            st.write("Dane z arkusza Gratis Zgaginstop 24:")
            st.write(Lg.head())
            
        if 'Gratis Zgaginstop 48' in xls.sheet_names:
            Lgr = pd.read_excel(df, sheet_name='Gratis Zgaginstop 48', skiprows=14, usecols=[1, 3, 9])
            st.write("Dane z arkusza Gratis Zgaginstop 48:")
            st.write(Lgr.head())



        #usuń braki danych z Kod klienta
        
        Lr = Lr.dropna(subset=['Pakiet']) 
        Lg = Lg.dropna(subset=['Pakiet']) 
        Lra = Lra.dropna(subset=['Pakiet']) 
        Lgr = Lgr.dropna(subset=['Pakiet']) 

        Lg = Lg[~Lg['Pakiet'].str.lower().str.contains('brak')]
        Lgr = Lgr[~Lgr['Pakiet'].str.lower().str.contains('brak')]

        Lr = Lr.dropna(subset=['Klient'])
        Lra = Lra.dropna(subset=['Klient'])
        # klient na całkowite
        Lr['Klient'] = Lr['Klient'].astype(int)
        Lg['Klient'] = Lg['Klient'].astype(int)
        Lra['Klient'] = Lra['Klient'].astype(int)
        Lgr['Klient'] = Lgr['Klient'].astype(int)



        Lr.columns=['Klient','Kod SAP','Pakiet']
        Lra.columns=['Klient','Kod SAP','Pakiet']
 
        
        # Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
        Lr['SIECIOWY'] = Lr.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
        Lg['SIECIOWY'] = Lg.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
        Lra['SIECIOWY'] = Lra.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
        Lgr['SIECIOWY'] = Lgr.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)

        Lr['Pakiet'] = Lr['Pakiet'].apply(extract_percentage)
        Lra['Pakiet'] = Lra['Pakiet'].apply(extract_percentage)

        Lg['pakiet'] = Lg['Pakiet'].apply(extract_numbers_as_text)
        Lgr['pakiet'] = Lgr['Pakiet'].apply(extract_numbers_as_text)



        #Lg

        # na zmiennoprzecinkowe
        Lr['Pakiet'] = Lr['Pakiet'].apply(percentage_to_float)
        Lra['Pakiet'] = Lra['Pakiet'].apply(percentage_to_float)
    
        # Dodaj nową kolumnę 'max_percent'
        Lr1 = Lr[Lr['SIECIOWY'] == 'SIECIOWY']
        Lr2 = Lr[Lr['SIECIOWY'] != 'SIECIOWY']
        Lr1['max_percent'] = Lr1[['Pakiet']].max(axis=1)
        Lr2['max_percent'] = Lr2[['Pakiet']].max(axis=1)

        Lra1 = Lra[Lra['SIECIOWY'] == 'SIECIOWY']
        Lra2 = Lra[Lra['SIECIOWY'] != 'SIECIOWY']
        Lra1['max_percent'] = Lra1[['Pakiet']].max(axis=1)
        Lra2['max_percent'] = Lra2[['Pakiet']].max(axis=1)
        
        ###### 1 to SIECIOWI, 2 to punkt dostaw
        Lr1 = Lr1[['Klient','Kod SAP','max_percent']]
        Lr2 = Lr2[['Kod SAP','max_percent']]

        Lra1 = Lra1[['Klient','Kod SAP','max_percent']]
        Lra2 = Lra2[['Kod SAP','max_percent']]


        Lg1 = Lg[Lg['SIECIOWY'] == 'SIECIOWY']
        Lg2 = Lg[Lg['SIECIOWY'] != 'SIECIOWY']
        
        Lgr1 = Lgr[Lgr['SIECIOWY'] == 'SIECIOWY']
        Lgr2 = Lgr[Lgr['SIECIOWY'] != 'SIECIOWY']


        
        #### p
        Lg1 = Lg1[['Klient','Kod SAP','pakiet']]
        Lg2 = Lg2[['Kod SAP','pakiet']]

        Lgr1 = Lgr1[['Klient','Kod SAP','pakiet']]
        Lgr2 = Lgr2[['Kod SAP','pakiet']]
        
        stand_lr = Lr2
        pow_lr = Lr1
        
        stand_lra = Lra2
        pow_lra = Lra1

        stand_lg = Lg2
        pow_lg = Lg1

        
        stand_lgr = Lgr2
        pow_lgr = Lgr1
        
        #TERAZ IMS
        ims = st.file_uploader(
            label = "Wrzuć plik ims_nhd"
        )
    
        if ims:
            ims = pd.read_excel(ims, usecols=[0,2,19,21])
            st.write(ims.head())
    
        ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
        ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]
    
        wynik_df_lr = pd.merge(pow_lr, ims, left_on='Klient', right_on='Klient', how='left')
        wynik_df_lg = pd.merge(pow_lg, ims, left_on='Klient', right_on='Klient', how='left')
        wynik_df_lra = pd.merge(pow_lra, ims, left_on='Klient', right_on='Klient', how='left')
        wynik_df_lgr = pd.merge(pow_lgr, ims, left_on='Klient', right_on='Klient', how='left')
    
        # Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
        wynik_df_lr = wynik_df_lr[['Klient','APD_kod_SAP_apteki', 'max_percent']]
        wynik_df_lg = wynik_df_lg[['Klient','APD_kod_SAP_apteki', 'pakiet']]

        wynik_df_lra = wynik_df_lra[['Klient','APD_kod_SAP_apteki', 'max_percent']]
        wynik_df_lgr = wynik_df_lgr[['Klient','APD_kod_SAP_apteki', 'pakiet']]
    
        #to są kody SAP
        wynik_df1_lr = wynik_df_lr.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1_lr = wynik_df1_lr[['Kod SAP','max_percent']]

        wynik_df1_lra = wynik_df_lra.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1_lra = wynik_df1_lra[['Kod SAP','max_percent']]

        wynik_df1_lg = wynik_df_lg.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1_lg = wynik_df1_lg[['Kod SAP','pakiet']]

        wynik_df1_lgr = wynik_df_lgr.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1_lgr = wynik_df1_lgr[['Kod SAP','pakiet']]

        #wynik_df1
    
        #to są kody powiazan
        wynik_df2_lr = wynik_df_lr.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2_lr = wynik_df2_lr[['Kod SAP','max_percent']]

        wynik_df2_lra = wynik_df_lra.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2_lra = wynik_df2_lra[['Kod SAP','max_percent']]

        wynik_df2_lg = wynik_df_lg.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2_lg = wynik_df2_lg[['Kod SAP','pakiet']]

        wynik_df2_lgr = wynik_df_lgr.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2_lgr = wynik_df2_lgr[['Kod SAP','pakiet']]

        #wynik_df2

        #POŁĄCZYĆ wynik_df z standard_ost
        polaczone_lr = pd.concat([stand_lr, wynik_df1_lr, wynik_df2_lr], axis = 0)
        polaczone_lra = pd.concat([stand_lra, wynik_df1_lra, wynik_df2_lra], axis = 0)

        polaczone_lg = pd.concat([stand_lg, wynik_df1_lg, wynik_df2_lg], axis = 0)
        polaczone_lgr = pd.concat([stand_lgr, wynik_df1_lgr, wynik_df2_lgr], axis = 0)
  
        posortowane_lr = polaczone_lr.sort_values(by='max_percent', ascending=False)
        posortowane_lra = polaczone_lra.sort_values(by='max_percent', ascending=False)

        ostatecznie_lr = posortowane_lr.drop_duplicates(subset='Kod SAP')
        ostatecznie_lr = ostatecznie_lr[ostatecznie_lr['max_percent'] != 0]

        ostatecznie_lra = posortowane_lra.drop_duplicates(subset='Kod SAP')
        ostatecznie_lra = ostatecznie_lra[ostatecznie_lra['max_percent'] != 0]


        ostatecznie_lg = polaczone_lg.drop_duplicates(subset=['Kod SAP', 'pakiet'])
        ostatecznie_lgr = polaczone_lgr.drop_duplicates(subset=['Kod SAP', 'pakiet'])

        OST = pd.concat(
        [
        ostatecznie_lr["Kod SAP"],
        ostatecznie_lra["Kod SAP"],
        ostatecznie_lg["Kod SAP"],
        ostatecznie_lgr["Kod SAP"],
        ],
        ignore_index=True
            ).drop_duplicates().to_frame(name="Kod SAP")

        # ostatecznie_lg
        
        st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
        excel_file = io.BytesIO()

        with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        # Jeśli dane BRAZOFLAMIN istnieją, zapisz je w odpowiednim arkuszu
            if 'ostatecznie_lr' in locals():
                ostatecznie_lr.to_excel(writer, index=False, sheet_name='Rabat Zgaginstop 24')
            if 'ostatecznie_lra' in locals():
                ostatecznie_lra.to_excel(writer, index=False, sheet_name='Rabat Zgaginstop 48')

            if 'ostatecznie_lg' in locals():
                ostatecznie_lg.to_excel(writer, index=False, sheet_name='Gratis Zgaginstop 24')
            if 'ostatecznie_lgr' in locals():
                ostatecznie_lgr.to_excel(writer, index=False, sheet_name='Gratis Zgaginstop 48')
                
            if 'OST' in locals():
                OST.to_excel(writer, index=False, sheet_name='Połączone')

        excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

         # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz, jeśli to pierwszy monitoring',
            data=excel_file,
            file_name='czy_dodac.xlsx',
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
    
        # Plik z poprzedniego monitoringu
        poprzedni = st.file_uploader(
            label="Wrzuć plik z poprzedniego monitoringu"
        )
    
        if poprzedni:
            xls = pd.ExcelFile(poprzedni)  # Pobranie pliku z arkuszami
    
        # Wczytanie danych z odpowiednich arkuszy
        if 'Rabat Zgaginstop 24' in xls.sheet_names:
            poprzedni_lr = pd.read_excel(poprzedni, sheet_name='Rabat Zgaginstop 24')
            st.write('Poprzedni monitoring - Rabat Zgaginstop 24:')
            st.write(poprzedni_lr.head())

        if 'Rabat Zgaginstop 48' in xls.sheet_names:
            poprzedni_lra = pd.read_excel(poprzedni, sheet_name='Rabat Zgaginstop 48')
            st.write('Poprzedni monitoring - Rabat Zgaginstop 48:')
            st.write(poprzedni_lra.head())

        if 'Gratis Zgaginstop 24' in xls.sheet_names:
            poprzedni_lg = pd.read_excel(poprzedni, sheet_name='Gratis Zgaginstop 24')
            st.write('Poprzedni monitoring - Gratis Zgaginstop 24:')
            st.write(poprzedni_lg.head())

        if 'Gratis Zgaginstop 48' in xls.sheet_names:
            poprzedni_lgr = pd.read_excel(poprzedni, sheet_name='Gratis Zgaginstop 48')
            st.write('Poprzedni monitoring - Gratis Zgaginstop 48:')
            st.write(poprzedni_lgr.head())

        if 'Połączone' in xls.sheet_names:
            poprzedni_OST = pd.read_excel(poprzedni, sheet_name='Połączone')
            st.write('Poprzedni monitoring - Połączone:')
            st.write(poprzedni_OST.head())

        # Przetwarzanie 
        if 'ostatecznie_lr' in locals() and 'poprzedni_lr' in locals():
            poprzedni_lr = poprzedni_lr.rename(columns={'max_percent': 'old_percent'})
            result_lr = ostatecznie_lr.merge(poprzedni_lr[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
            result_lr['old_percent'] = result_lr['old_percent'].fillna(0)
            result_lr['Czy dodać'] = result_lr.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)

        if 'ostatecznie_lra' in locals() and 'poprzedni_lra' in locals():
            poprzedni_lra = poprzedni_lra.rename(columns={'max_percent': 'old_percent'})
            result_lra = ostatecznie_lra.merge(poprzedni_lra[['Kod SAP', 'old_percent']], on='Kod SAP', how='left')
            result_lra['old_percent'] = result_lra['old_percent'].fillna(0)
            result_lra['Czy dodać'] = result_lra.apply(lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '', axis=1)

        if 'ostatecznie_lg' in locals() and 'poprzedni_lg' in locals():
            result_lg = pd.concat([ostatecznie_lg, poprzedni_lg], ignore_index=True)
            # Usuń duplikaty na podstawie kluczowych kolumn (zachowując pierwsze wystąpienie)
            result_lg = result_lg.drop_duplicates(subset=['Kod SAP', 'pakiet'], keep='first')
            # Oznacz nowe wiersze (takie, które nie były w poprzedni_lg)
            result_lg['Czy dodać'] = result_lg.apply(lambda row: 'DODAJ' if row['Kod SAP'] not in poprzedni_lg['Kod SAP'].values 
                                                     or row['pakiet'] not in poprzedni_lg['pakiet'].values else '', axis=1)

        if 'ostatecznie_lgr' in locals() and 'poprzedni_lgr' in locals():
            result_lgr = pd.concat([ostatecznie_lgr, poprzedni_lgr], ignore_index=True)
            # Usuń duplikaty na podstawie kluczowych kolumn (zachowując pierwsze wystąpienie)
            result_lgr = result_lgr.drop_duplicates(subset=['Kod SAP', 'pakiet'], keep='first')
            # Oznacz nowe wiersze (takie, które nie były w poprzedni_lg)
            result_lgr['Czy dodać'] = result_lgr.apply(lambda row: 'DODAJ' if row['Kod SAP'] not in poprzedni_lgr['Kod SAP'].values 
                                                     or row['pakiet'] not in poprzedni_lgr['pakiet'].values else '', axis=1)

        if 'OST' in locals() and 'poprzedni_OST' in locals():
            result_OST = pd.concat([OST, poprzedni_OST], ignore_index=True)

            # usuń duplikaty Kod SAP (zachowaj pierwsze)
            result_OST = result_OST.drop_duplicates(subset=['Kod SAP'], keep='first')

            # oznacz nowe kody SAP
            result_OST['Czy dodać'] = result_OST['Kod SAP'].apply(
                lambda x: 'DODAJ' if x not in poprzedni_OST['Kod SAP'].values else ''
            )



        # Zapisywanie plików do Excela
        excel_file1 = io.BytesIO()
        with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
            if 'result_lr' in locals():
                result_lr.to_excel(writer, index=False, sheet_name='Rabat Zgaginstop 24')
            if 'result_lra' in locals():
                result_lra.to_excel(writer, index=False, sheet_name='Rabat Zgaginstop 48')
            if 'result_lg' in locals():
                result_lg.to_excel(writer, index=False, sheet_name='Gratis Zgaginstop 24')
            if 'result_lgr' in locals():
                result_lgr.to_excel(writer, index=False, sheet_name='Gratis Zgaginstop 48')
            if 'result_OST' in locals():
                result_OST.to_excel(writer, index=False, sheet_name='Połączone')


        excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

        # Definiowanie nazwy pliku
        nazwa_pliku = f"ZGAGINSTOP_{dzisiejsza_data}.xlsx"
        # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Kliknij aby pobrać plik z kodami, które kody należy dodać',
            data=excel_file1,
            file_name=nazwa_pliku,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )

        result_lr = result_lr.drop(columns=['old_percent', 'Czy dodać'])
        result_lg = result_lg.drop(columns=['Czy dodać'])
        result_lra = result_lra.drop(columns=['old_percent', 'Czy dodać'])
        result_lgr = result_lgr.drop(columns=['Czy dodać'])
        result_OST = result_OST.drop(columns=['Czy dodać'])
        # result_lg = result_lg.drop(columns=['old_pakiet', 'Czy dodać'])

        st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')

        # Tworzenie pliku Excel w pamięci
        excel_file2 = io.BytesIO()
    
        # Zapis do pliku Excel w pamięci
        with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
            result_lr.to_excel(writer, index=False, sheet_name='Rabat Zgaginstop 24')
            result_lra.to_excel(writer, index=False, sheet_name='Rabat Zgaginstop 48')
            result_lg.to_excel(writer, index=False, sheet_name='Gratis Zgaginstop 24')
            result_lgr.to_excel(writer, index=False, sheet_name='Gratis Zgaginstop 48')
            result_OST.to_excel(writer, index=False, sheet_name='Połączone')


        # Resetowanie wskaźnika do początku pliku
        excel_file2.seek(0) 
    
        # Definiowanie nazwy pliku
        nazwa_pliku = f"FM_ZGAGINSTOP_{dzisiejsza_data}.xlsx"
    
        # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz nowy plik FORMUŁA MAX',
            data=excel_file2,
            file_name=nazwa_pliku,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )


############################################################################### OFERTA SEZONOWA  ##############################################################################################
if sekcja == 'Oferta sezonowa':
    st.write(tabs_font_css, unsafe_allow_html=True)

    df = st.file_uploader(
        label="Wrzuć plik - Oferta sezonowa"
    )
    
    if df:
        # Pobieramy listę dostępnych arkuszy
        xls = pd.ExcelFile(df)
        
        # Sprawdzamy, które arkusze są dostępne i wczytujemy odpowiednie dane
        if 'Rabat' in xls.sheet_names:
            Lr = pd.read_excel(df, sheet_name='Rabat', skiprows=13, usecols=[1, 3, 9])
            st.write("Dane z arkusza Rabat:")
            st.write(Lr.head())


        # Sprawdzamy, które arkusze są dostępne i wczytujemy odpowiednie dane
        if 'Gratis' in xls.sheet_names:
            Lg = pd.read_excel(df, sheet_name='Gratis', skiprows=7, usecols=[1, 3, 9])
            st.write("Dane z arkusza Gratis:")
            st.write(Lg.head())


        Lr = Lr.dropna(subset=['Pakiet']) 
        Lg = Lg.dropna(subset=['Pakiet']) 

        Lg = Lg[~Lg['Pakiet'].str.lower().str.contains('brak')]

        Lr = Lr.dropna(subset=['Klient'])
        # klient na całkowite
        Lr['Klient'] = Lr['Klient'].astype(int)
        Lg['Klient'] = Lg['Klient'].astype(int)
        Lg['Indeks'] = Lg['Indeks'].astype(int)



        Lr.columns=['Klient','Kod SAP','Pakiet']
 
        
        # Dodaj kolumnę 'SIECIOWY', która będzie zawierać 'SIECIOWY' jeśli w kolumnach '12' lub '14' jest słowo 'powiązanie'
        Lr['SIECIOWY'] = Lr.apply(lambda row: 'SIECIOWY' if 'powiązanie' in str(row['Pakiet']).lower() else '', axis=1)
        

        Lr['Pakiet'] = Lr['Pakiet'].apply(extract_percentage)

        Lg['pakiet'] = Lg['Pakiet'].apply(extract_numbers_as_text)
        
        wykluczone_indeksy = [117792, 123364, 123017]
        Lg = Lg[~Lg['Indeks'].isin(wykluczone_indeksy)]
        Lg['SIECIOWY'] = 'SIECIOWY'
        Lg

        # na zmiennoprzecinkowe
        Lr['Pakiet'] = Lr['Pakiet'].apply(percentage_to_float)
    
        # Dodaj nową kolumnę 'max_percent'
        Lr1 = Lr[Lr['SIECIOWY'] == 'SIECIOWY']
        Lr2 = Lr[Lr['SIECIOWY'] != 'SIECIOWY']
        Lr1['max_percent'] = Lr1[['Pakiet']].max(axis=1)
        Lr2['max_percent'] = Lr2[['Pakiet']].max(axis=1)
        
        ###### 1 to SIECIOWI, 2 to punkt dostaw
        Lr1 = Lr1[['Klient','Kod SAP','max_percent']]
        Lr2 = Lr2[['Kod SAP','max_percent']]

        
        #### p
        Lg1 = Lg[['Klient','Indeks','pakiet']]

        stand_lr = Lr2
        pow_lr = Lr1

        pow_lg = Lg1
        pow_lg['Logiczne'] = pow_lg['Indeks'].astype(str) + '_' + pow_lg['pakiet'].astype(str)


        mapa_nielogiczne = {
        '117226_80+30': '117226_3+2',
        '117790_80+30': '117790_10+6',
        '99954_50+20': '99954_5+2',
        '79580_40+15': '79580_3+1',
        '99938_40+15': '99938_2+1',
        '120002_50+15': '120002_4+2',
        '97047_150+75': '97047_5+2',
        '97048_100+30': '97048_10+3',
        '97049_50+15': '97049_10+3',
        '97050_100+30': '97050_15+8',
        '97051_100+30': '97051_10+3',
        '97052_50+15': '97052_5+2',
        '112551_50+20': '112551_5+2',
        '112550_50+20': '112550_5+2',
        '114535_30+10': '114535_3+1',
        '97072_100+40': '97072_10+4',
        '97073_100+40': '97073_10+4',
        '116878_100+40': '116878_5+2',
        '116929_50+20': '116929_4+2',
        '70034_30+15': '70034_4+2',
        '65805_40+15': '65805_5+2',
        '110155_40+15': '110155_5+2',
        '97042_300+160': '97042_8+3',
        '97044_200+110': '97044_8+3',
        '97045_100+55': '97045_10+3',
        '74004_30+15': '74004_5+2',
        '121724_50+20': '121724_10+4',
        '122696_50+20': '122696_10+4',
        }
        
        pow_lg['Nielogiczne'] = pow_lg['Logiczne'].map(mapa_nielogiczne)


        pow_lg

        
        #TERAZ IMS
        ims = st.file_uploader(
            label = "Wrzuć plik ims_nhd"
        )
    
        if ims:
            ims = pd.read_excel(ims, usecols=[0,2,19,21])
            st.write(ims.head())
    
        ims = ims[ims['APD_Czy_istnieje_na_rynku']==1]
        ims = ims[ims['APD_Rodzaj_farmaceutyczny'].isin(['AP - Apteka','ME - Sklep zielarsko - medyczny','PU - Punkt apteczny'])]
    
        wynik_df_lr = pd.merge(pow_lr, ims, left_on='Klient', right_on='Klient', how='left')
        
        wynik_df_lg = pd.merge(pow_lg, ims, left_on='Klient', right_on='Klient', how='left')
    
        # Wybór potrzebnych kolumn: 'APD_kod_SAP_apteki' i 'max_percent'
        wynik_df_lr = wynik_df_lr[['Klient','APD_kod_SAP_apteki', 'max_percent']]
        wynik_df_lg = wynik_df_lg[['Klient','APD_kod_SAP_apteki', 'Indeks', 'Nielogiczne']]
    
        #to są kody SAP
        wynik_df1_lr = wynik_df_lr.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1_lr = wynik_df1_lr[['Kod SAP','max_percent']]

        wynik_df1_lg = wynik_df_lg.rename(columns={'APD_kod_SAP_apteki': 'Kod SAP'})
        wynik_df1_lg = wynik_df1_lg[['Kod SAP','Indeks','Nielogiczne']]

        #wynik_df1
    
        #to są kody powiazan
        wynik_df2_lr = wynik_df_lr.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2_lr = wynik_df2_lr[['Kod SAP','max_percent']]

        wynik_df2_lg = wynik_df_lg.rename(columns={'Klient': 'Kod SAP'})
        wynik_df2_lg = wynik_df2_lg[['Kod SAP','Indeks','Nielogiczne']]

        #wynik_df2

        #POŁĄCZYĆ wynik_df z standard_ost
        polaczone_lr = pd.concat([stand_lr, wynik_df1_lr, wynik_df2_lr], axis = 0)

        polaczone_lg = pd.concat([wynik_df1_lg, wynik_df2_lg], axis = 0)
  
        posortowane_lr = polaczone_lr.sort_values(by='max_percent', ascending=False)

        ostatecznie_lr = posortowane_lr.drop_duplicates(subset='Kod SAP')
        ostatecznie_lr = ostatecznie_lr[ostatecznie_lr['max_percent'] != 0]


        ostatecznie_lg = polaczone_lg.drop_duplicates(subset=['Kod SAP', 'Indeks', 'Nielogiczne'])

        grupa_1 = [117226, 117790, 99954, 79580, 99938, 120002, 97047]
        grupa_2 = [97048, 97049, 97050, 97051, 97052, 112551, 112550]
        grupa_3 = [114535, 97072, 97073, 116878, 116929, 70034, 65805]
        grupa_4 = [110155, 97042, 97044, 97045, 74004, 121724, 122696]


        pierwszy = ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_1)]
        drugi = ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_2)]
        trzeci = ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_3)]
        czwarty = ostatecznie_lg[ostatecznie_lg['Indeks'].isin(grupa_4)]



        # ostatecznie_lg
        
        st.write('Jeśli to pierwszy monitoring, pobierz ten plik, jeśli nie, wrzuć plik z poprzedniego monitoringu i NIE POBIERAJ TEGO PLIKU')
        excel_file = io.BytesIO()
        
        with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
        
            # arkusz bez zmian
            if 'ostatecznie_lr' in locals():
                ostatecznie_lr.to_excel(writer, index=False, sheet_name='Rabat')
        
            # grupy LG w osobnych arkuszach
            if 'pierwszy' in locals():
                pierwszy.to_excel(writer, index=False, sheet_name='pierwszy')
        
            if 'drugi' in locals():
                drugi.to_excel(writer, index=False, sheet_name='drugi')
        
            if 'trzeci' in locals():
                trzeci.to_excel(writer, index=False, sheet_name='trzeci')
        
            if 'czwarty' in locals():
                czwarty.to_excel(writer, index=False, sheet_name='czwarty')


        excel_file.seek(0)  # Resetowanie wskaźnika do początku pliku

         # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Pobierz, jeśli to pierwszy monitoring',
            data=excel_file,
            file_name='czy_dodac.xlsx',
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )

        # Plik z poprzedniego monitoringu 
        poprzedni = st.file_uploader(label="Wrzuć plik z poprzedniego monitoringu")
    
        # Plik z poprzedniego monitoringu
        if poprzedni:
            xls = pd.ExcelFile(poprzedni)
        
        # Rabat – bez zmian
        if 'Rabat' in xls.sheet_names:
            poprzedni_lr = pd.read_excel(poprzedni, sheet_name='Rabat')
            st.write('Poprzedni monitoring - Rabat:')
            st.write(poprzedni_lr.head())
        
        # Gratis – 4 grupy
        poprzedni_gratis = {}
        
        for nazwa in ['pierwszy', 'drugi', 'trzeci', 'czwarty']:
            if nazwa in xls.sheet_names:
                poprzedni_gratis[nazwa] = pd.read_excel(poprzedni, sheet_name=nazwa)
                st.write(f'Poprzedni monitoring - {nazwa}:')
                st.write(poprzedni_gratis[nazwa].head())


        if 'ostatecznie_lr' in locals() and 'poprzedni_lr' in locals():
            poprzedni_lr = poprzedni_lr.rename(columns={'max_percent': 'old_percent'})
            result_lr = ostatecznie_lr.merge(
                poprzedni_lr[['Kod SAP', 'old_percent']],
                on='Kod SAP',
                how='left'
            )
            result_lr['old_percent'] = result_lr['old_percent'].fillna(0)
            result_lr['Czy dodać'] = result_lr.apply(
                lambda row: 'DODAJ' if row['max_percent'] > row['old_percent'] else '',
                axis=1
            )

        wyniki_gratis = {}
        
        mapa_grup = {
            'pierwszy': pierwszy,
            'drugi': drugi,
            'trzeci': trzeci,
            'czwarty': czwarty,
        }

        
        for nazwa, df_aktualny in mapa_grup.items():
        
            df_poprzedni = poprzedni_gratis.get(nazwa)
        
            if df_poprzedni is not None:
                result = pd.concat([df_aktualny, df_poprzedni], ignore_index=True)
        
                result = result.drop_duplicates(
                    subset=['Kod SAP', 'pakiet'],
                    keep='first'
                )
        
                result['Czy dodać'] = result.apply(
                    lambda row: 'DODAJ'
                    if not (
                        (row['Kod SAP'] in df_poprzedni['Kod SAP'].values)
                        and (row['pakiet'] in df_poprzedni['pakiet'].values)
                    )
                    else '',
                    axis=1
                )
            else:
                result = df_aktualny.copy()
                result['Czy dodać'] = 'DODAJ'
        
            wyniki_gratis[nazwa] = result


        excel_file1 = io.BytesIO()
        
        with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
        
            if 'result_lr' in locals():
                result_lr.to_excel(writer, index=False, sheet_name='Rabat')
        
            for nazwa, df in wyniki_gratis.items():
                df.to_excel(writer, index=False, sheet_name=nazwa)

        excel_file1.seek(0)  # Resetowanie wskaźnika do początku pliku

        # Definiowanie nazwy pliku
        nazwa_pliku = f"OFERTA_SEZONOWA_{dzisiejsza_data}.xlsx"
        # Umożliwienie pobrania pliku Excel
        st.download_button(
            label='Kliknij aby pobrać plik z kodami, które kody należy dodać',
            data=excel_file1,
            file_name=nazwa_pliku,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )



####################################### TU SKONCZYŁAM




        # Rabat – bez zmian
        result_lr = result_lr.drop(columns=['old_percent', 'Czy dodać'], errors='ignore')
        
        # Gratis – każda grupa osobno
        for nazwa in wyniki_gratis:
            wyniki_gratis[nazwa] = wyniki_gratis[nazwa].drop(
                columns=['Czy dodać'],
                errors='ignore'
            )


        st.write('Kliknij, aby pobrać plik z formułą max do następnego monitoringu')


        excel_file2 = io.BytesIO()

        with pd.ExcelWriter(excel_file2, engine='xlsxwriter') as writer:
        
            # Rabat
            result_lr.to_excel(writer, index=False, sheet_name='Rabat')
        
            # Gratis – 4 arkusze
            for nazwa, df in wyniki_gratis.items():
                df.to_excel(writer, index=False, sheet_name=nazwa)


        excel_file2.seek(0)
        
        nazwa_pliku = f"FM_OFERTA_SEZONOWA_{dzisiejsza_data}.xlsx"
        
        st.download_button(
            label='Pobierz nowy plik FORMUŁA MAX',
            data=excel_file2,
            file_name=nazwa_pliku,
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )







        






    
    







        


















    
